"""Sample employee data for the mock server."""

SAMPLE_EMPLOYEES = [
    {
        "id": "8c8c13b6-35ed-3ffb-92d5-c438825df67f",
        "date_of_birth": "1990-06-29",
        "image": "https://lorempixel.com/640/480/people/?96612",
        "email": "andres34@gmail.com",
        "first_name": "Dayni",
        "last_name": "Mayez",
        "title": "Mr.",
        "address": "18342 Alisa Square Suite 259",
        "country": "USA",
        "bio": "Software engineer with expertise in backend development.",
        "rating": "3.0600000000000001",
    },
    {
        "id": "a1b2c3d4-5678-9abc-def0-123456789abc",
        "date_of_birth": "1985-03-15",
        "image": "https://lorempixel.com/640/480/people/?12345",
        "email": "jane.smith@example.com",
        "first_name": "Jane",
        "last_name": "Smith",
        "title": "Ms.",
        "address": "456 Oak Avenue, Suite 100",
        "country": "Canada",
        "bio": "Product manager with 10 years of experience in tech.",
        "rating": "4.5",
    },
    {
        "id": "b2c3d4e5-6789-abcd-ef01-23456789abcd",
        "date_of_birth": "1992-11-22",
        "image": "https://lorempixel.com/640/480/people/?67890",
        "email": "bob.wilson@company.org",
        "first_name": "Bob",
        "last_name": "Wilson",
        "title": "Dr.",
        "address": "789 Pine Street",
        "country": "USA",
        "bio": "Data scientist specializing in machine learning.",
        "rating": "4.2",
    },
    {
        "id": "c3d4e5f6-789a-bcde-f012-3456789abcde",
        "date_of_birth": "1988-07-08",
        "image": "https://lorempixel.com/640/480/people/?11111",
        "email": "alice.johnson@tech.io",
        "first_name": "Alice",
        "last_name": "Johnson",
        "title": "Mrs.",
        "address": "321 Maple Drive",
        "country": "UK",
        "bio": "UX designer passionate about user-centered design.",
        "rating": "3.8",
    },
    {
        "id": "d4e5f6a7-89ab-cdef-0123-456789abcdef",
        "date_of_birth": "1995-01-30",
        "image": "https://lorempixel.com/640/480/people/?22222",
        "email": "carlos.garcia@startup.com",
        "first_name": "Carlos",
        "last_name": "Garcia",
        "title": "Mr.",
        "address": "555 Tech Boulevard",
        "country": "USA",
        "bio": "Full-stack developer with a focus on React and Node.js.",
        "rating": "4.7",
    },
    {
        "id": "e5f6a7b8-9abc-def0-1234-56789abcdef0",
        "date_of_birth": "1983-09-12",
        "image": "https://lorempixel.com/640/480/people/?33333",
        "email": "emma.brown@enterprise.net",
        "first_name": "Emma",
        "last_name": "Brown",
        "title": "Ms.",
        "address": "888 Corporate Lane",
        "country": "Canada",
        "bio": "DevOps engineer with cloud infrastructure expertise.",
        "rating": "4.0",
    },
    {
        "id": "f6a7b8c9-abcd-ef01-2345-6789abcdef01",
        "date_of_birth": "1991-04-25",
        "image": "https://lorempixel.com/640/480/people/?44444",
        "email": "michael.lee@agency.co",
        "first_name": "Michael",
        "last_name": "Lee",
        "title": "Mr.",
        "address": "222 Design Street",
        "country": "UK",
        "bio": "Creative director leading brand strategy initiatives.",
        "rating": "3.5",
    },
    {
        "id": "a7b8c9d0-bcde-f012-3456-789abcdef012",
        "date_of_birth": "1987-12-05",
        "image": "https://lorempixel.com/640/480/people/?55555",
        "email": "sarah.davis@consulting.com",
        "first_name": "Sarah",
        "last_name": "Davis",
        "title": "Mrs.",
        "address": "999 Business Park",
        "country": "USA",
        "bio": "Management consultant specializing in digital transformation.",
        "rating": "4.9",
    },
]
